export const SITE = {
  website: "https://fucov.github.io/",
  author: "Fucov",
  profile: "https://github.com/Fucov",
  desc: "Fucov的个人博客，记录 AI Infra、推荐系统与 Agents 相关的工程实践与思考。",
  title: "Fucov",
  ogImage: "",
  lightAndDarkMode: true,
  postPerIndex: 4,
  postPerPage: 4,
  scheduledPostMargin: 15 * 60 * 1000,
  showArchives: true,
  showBackButton: true,
  editPost: {
    enabled: true,
    text: "Edit page",
    url: "https://github.com/Fucov/Fucov.github.io/edit/main/",
  },
  dynamicOgImage: true,
  dir: "ltr",
  lang: "zh-CN",
  timezone: "Asia/Shanghai",
} as const;
